use airbnb_analysis;

CREATE TABLE listings (
  Listing_ID                     BIGINT         NOT NULL PRIMARY KEY,
  Apartment_Type                 VARCHAR(255)   NULL,
  Host_ID                        BIGINT         NULL,
  Host_Name                      VARCHAR(100)   NULL,
  Neighbourhood_County           VARCHAR(100)   NULL,
  Neighbourhood                  VARCHAR(100)   NULL,
  Latitude                            DECIMAL(8,5)   NULL,
  Longitude                         DECIMAL(8,5)   NULL,
  Country                        VARCHAR(100)   NULL,
  Instant_Bookable               BOOLEAN        NULL,
  Cancellation_Policy            VARCHAR(50)    NULL,
  Room_Type                      VARCHAR(50)    NULL,
  Construction_Type              SMALLINT       NULL,
  Price                          INT            NULL,
  Service_Year                   SMALLINT       NULL,
  Minimum_Nights                 INT            NULL,
  Number_Of_Reviews              INT            NULL,
  Last_Review                    DATE           NULL,
  Reviews_Per_Month              DECIMAL(5,2)   NULL,
  Review_Rate_Number             TINYINT        NULL,
  Calculated_Host_Listings_Count INT            NULL,
  Availability_Days              INT            NULL
) 

SELECT * FROM LISTINGS;

LOAD DATA INFILE 'C:/ProgramData/MySQL\MySQL Server 8.0/Uploads/Airbnb_Open_Data.csv' INTO TABLE LISTINGS
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

LOAD DATA INFILE 'C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\Airbnb_Open_Data.csv'
INTO TABLE listings
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','  
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(
  Listing_ID,
  Apartment_Type,
  Host_ID,
  Host_Name,
  Neighbourhood_County,
  Neighbourhood,
  Latitude,
  longitude,
  Country,
  Instant_Bookable,
  Cancellation_Policy,
  Room_Type,
  Construction_Type,
  Price,
  Service_Year,
  Minimum_Nights,
  Number_Of_Reviews,
  @Last_Review,
  Reviews_Per_Month,
  Review_Rate_Number,
  Calculated_Host_Listings_Count,
  Availability_Days
)
SET
  Last_Review = STR_TO_DATE(@Last_Review, '%m/%d/%Y');
  
SELECT * FROM LISTINGS;

-- COUNT OF LISTINGS
SELECT COUNT(LISTING_ID) AS COUNT FROM LISTINGS;

-- COUNT OF NEIGHBOURHOOD COUNT LISTINGS
SELECT NEIGHBOURHOOD_COUNTY, COUNT(LISTING_ID) AS COUNT 
FROM LISTINGS
GROUP BY NEIGHBOURHOOD_COUNTY;

-- FOUND FOUR NULL VALUES SO NEED TO DELETE
DELETE FROM LISTINGS
WHERE NEIGHBOURHOOD_COUNTY = 'Not found';

-- COUNT OF CONSTRUCTION YEAR 
SELECT CONSTRUCTION_TYPE, COUNT(APARTMENT_TYPE) AS COUNT
FROM LISTINGS
GROUP BY CONSTRUCTION_TYPE
ORDER BY CONSTRUCTION_TYPE ASC;

-- COUNT OF ROOM_TYPE IN DIFFERENT NEIGHBOURHOODS
SELECT NEIGHBOURHOOD, ROOM_TYPE , COUNT(*) AS COUNT 
FROM LISTINGS
GROUP BY NEIGHBOURHOOD, ROOM_TYPE;

-- COUNT OF BOOKINGS MADE IN EACH YEAR
SELECT YEAR(LAST_REVIEW) AS YEAR , COUNT(LISTING_ID) AS COUNT_OF_BOOKINGS 
FROM LISTINGS
GROUP BY YEAR(LAST_REVIEW)
ORDER BY YEAR(LAST_REVIEW) ASC;

-- TOP 5 NEIGHBOURHOODS
SELECT NEIGHBOURHOOD, COUNT(LISTING_ID) AS COUNT
FROM LISTINGS
GROUP BY NEIGHBOURHOOD
ORDER BY COUNT DESC
LIMIT 5;

-- MINIMUM, MAXIMUM, AVERAGE PRICE OF PROPERTIES
SELECT
  MIN(PRICE) AS MIN_PRICE,
  MAX(PRICE) AS MAX_PRICE,
  AVG(PRICE) AS AVG_PRICE
FROM LISTINGS;

-- LISTINGS WITH EXTREMELY HIGH PRICE (>1000)
SELECT * FROM LISTINGS
WHERE PRICE > 1000;

-- MONTHLY TRENDS
SELECT 
  YEAR(LAST_REVIEW) AS YEAR,
  MONTH(LAST_REVIEW) AS MONTH,
  COUNT(LISTING_ID) AS REVIEWS
FROM LISTINGS
WHERE LAST_REVIEW IS NOT NULL
GROUP BY YEAR(LAST_REVIEW), MONTH(LAST_REVIEW)
ORDER BY YEAR, MONTH;

-- AVERAGE PRICE PER NEIGHBOURHOOD
SELECT 
  NEIGHBOURHOOD, 
  AVG(PRICE) AS AVG_PRICE,
  COUNT(*) AS TOTAL_LISTINGS
FROM LISTINGS
GROUP BY NEIGHBOURHOOD
ORDER BY AVG_PRICE DESC
LIMIT 10;

-- DISTRIBUTION OF REVIEWS PER HOST
SELECT HOST_ID, NUMBER_OF_REVIEWS
FROM LISTINGS
ORDER BY NUMBER_OF_REVIEWS DESC
LIMIT 10;

-- HOST PERFORMANCE BY CANCELLATION POLICY OR ROOM TYPE
SELECT CANCELLATION_POLICY, AVG(REVIEW_RATE_NUMBER) AS AVG_RATING
FROM LISTINGS
GROUP BY CANCELLATION_POLICY;

-- BINS BASED ON PRICE
SELECT *,
  CASE 
    WHEN PRICE < 200 THEN 'LOW'
    WHEN PRICE BETWEEN 200 AND 800 THEN 'MEDIUM'
    ELSE 'HIGH'
  END AS PRICE_CATEGORY
FROM LISTINGS;

-- NEIGHBOURHOODS WITH HIGHEST AVG REVIEWS PER LISTING
SELECT 
  NEIGHBOURHOOD,
  AVG(NUMBER_OF_REVIEWS) AS AVG_REVIEWS
FROM LISTINGS
GROUP BY NEIGHBOURHOOD
ORDER BY AVG_REVIEWS DESC
LIMIT 10;

-- BEST RATED LISTINGS TOP 10 
SELECT * 
FROM LISTINGS
ORDER BY REVIEW_RATE_NUMBER DESC, NUMBER_OF_REVIEWS DESC
LIMIT 10;

-- LISTINGS WITH VERY LOW RATING
SELECT * 
FROM LISTINGS
WHERE REVIEW_RATE_NUMBER < 2;
-- ESTIMATED ANNUAL REVENUE
SELECT 
  LISTING_ID,
  PRICE,
  REVIEWS_PER_MONTH,
  ROUND(PRICE * REVIEWS_PER_MONTH * 12, 2) AS ESTIMATED_ANNUAL_REVENUE
FROM LISTINGS
WHERE PRICE IS NOT NULL AND REVIEWS_PER_MONTH IS NOT NULL
ORDER BY ESTIMATED_ANNUAL_REVENUE DESC
LIMIT 10;

SELECT * FROM listings
INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/listings_export.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

